import { describe,it,expect,vi } from 'vitest';
import { transferImage,bindQRImageTransfer } from '../web/qr-transfer';
const file=new File(['image'],'qr.png',{type:'image/png'});
const data=(image=true)=>({types:['Files'],items:image?[{kind:'file',type:'image/png',getAsFile:()=>file}]:[{kind:'file',type:'application/pdf',getAsFile:()=>new File(['pdf'],'x.pdf',{type:'application/pdf'})}],files:[]}) as unknown as DataTransfer;
function harness(open=true){const target=new EventTarget(),dialog=new EventTarget() as any;dialog.open=open;const classes=new Set<string>(),zone={classList:{add:(x:string)=>classes.add(x),remove:(x:string)=>classes.delete(x)}} as any,image=vi.fn(),error=vi.fn();bindQRImageTransfer(target,dialog,zone,image,error);return{target,dialog,classes,image,error};}
function emit(target:EventTarget,type:string,transfer:DataTransfer|null){const event=new Event(type,{cancelable:true});Object.defineProperty(event,type==='paste'?'clipboardData':'dataTransfer',{value:transfer});target.dispatchEvent(event);return event;}
describe('Clipboard and drag-drop QR images',()=>{
  it('extracts clipboard images and file-list fallback',()=>{expect(transferImage(data())).toBe(file);expect(transferImage({items:[],files:[file]} as any)).toBe(file);expect(transferImage(null)).toBe(null);});
  it('decodes pasted images only while Add account is open',()=>{const h=harness();expect(emit(h.target,'paste',data()).defaultPrevented).toBe(true);expect(h.image).toHaveBeenCalledWith(file);h.dialog.open=false;expect(emit(h.target,'paste',data()).defaultPrevented).toBe(false);expect(h.image).toHaveBeenCalledTimes(1);});
  it('preserves normal text pasting and ignores non-image clipboard files',()=>{const h=harness();for(const d of [null,{types:['text/plain'],items:[{kind:'string',type:'text/plain'}],files:[]} as any,data(false)])expect(emit(h.target,'paste',d).defaultPrevented).toBe(false);expect(h.image).not.toHaveBeenCalled();});
  it('highlights file drag, keeps highlight over child elements, and decodes a drop',()=>{const h=harness(),d=data();emit(h.target,'dragenter',d);emit(h.target,'dragenter',d);emit(h.target,'dragleave',d);expect(h.classes.has('drag-active')).toBe(true);expect(emit(h.target,'dragover',d).defaultPrevented).toBe(true);expect(d.dropEffect).toBe('copy');expect(emit(h.target,'drop',d).defaultPrevented).toBe(true);expect(h.image).toHaveBeenCalledWith(file);expect(h.classes.size).toBe(0);});
  it('blocks non-image file drops from navigating and reports a useful error',()=>{const h=harness();expect(emit(h.target,'drop',data(false)).defaultPrevented).toBe(true);expect(h.error).toHaveBeenCalledWith(expect.stringContaining('QR image'));expect(h.image).not.toHaveBeenCalled();});
  it('does not intercept drops outside the Add account flow and clears on close',()=>{const h=harness();emit(h.target,'dragenter',data());h.dialog.dispatchEvent(new Event('close'));expect(h.classes.size).toBe(0);h.dialog.open=false;expect(emit(h.target,'drop',data()).defaultPrevented).toBe(false);expect(h.image).not.toHaveBeenCalled();});
});
