import { describe, it, expect, vi, afterEach } from 'vitest';
import QRCode from 'qrcode';
import { readTOTPQR, QRScanner } from '../web/qr';
function image(text:string,inverted=false){const qr=QRCode.create(text,{errorCorrectionLevel:'M'}),scale=5,size=(qr.modules.size+8)*scale,data=new Uint8ClampedArray(size*size*4);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const mx=Math.floor(x/scale)-4,my=Math.floor(y/scale)-4;const dark=Boolean(mx>=0&&my>=0&&mx<qr.modules.size&&my<qr.modules.size&&qr.modules.get(mx,my));const value=(dark!==inverted)?0:255;const offset=(y*size+x)*4;data[offset]=data[offset+1]=data[offset+2]=value;data[offset+3]=255;}return {data,width:size,height:size};}
const uri='otpauth://totp/GitHub%3Ame%40example.com?secret=JBSWY3DPEHPK3PXP&issuer=GitHub';
describe('QR account decoding',()=>{
  for(const inverted of [false,true])it(`decodes an actual ${inverted?'inverted':'normal'} TOTP QR image`,()=>{const i=image(uri,inverted),result=readTOTPQR(i.data,i.width,i.height);expect(result?.uri).toBe(uri);expect(result?.account.issuer).toBe('GitHub');expect(result?.account.label).toBe('me@example.com');});
  it('rejects unrelated URLs, HOTP, and invalid TOTP secrets',()=>{for(const text of ['https://example.com','otpauth://hotp/test?secret=JBSWY3DPEHPK3PXP','otpauth://totp/test?secret=INVALID!']){const i=image(text);expect(()=>readTOTPQR(i.data,i.width,i.height)).toThrow('not a supported TOTP account');}});
  it('returns no result when an image contains no code',()=>{const data=new Uint8ClampedArray(100*100*4).fill(255);expect(readTOTPQR(data,100,100)).toBe(null);});
});
function harness(){const pixels=image(uri),canvas={width:0,height:0,getContext:()=>({drawImage:vi.fn(),getImageData:()=>pixels})};vi.stubGlobal('document',{createElement:()=>canvas});const video={pause:vi.fn(),play:vi.fn().mockResolvedValue(undefined),srcObject:null,readyState:2,videoWidth:pixels.width,videoHeight:pixels.height},panel={hidden:true},status=vi.fn(),found=vi.fn();const scanner=new QRScanner(video as any,panel as any,status,found);return{scanner,video,panel,status,found,canvas};}
afterEach(()=>vi.unstubAllGlobals());
describe('QR scanner lifecycle',()=>{
  it('requests video without audio, finds the account, and releases the camera',async()=>{const h=harness(),stop=vi.fn(),getUserMedia=vi.fn().mockResolvedValue({getTracks:()=>[{stop}]});vi.stubGlobal('navigator',{mediaDevices:{getUserMedia}});await h.scanner.camera();expect(getUserMedia).toHaveBeenCalledWith(expect.objectContaining({audio:false,video:expect.objectContaining({facingMode:{ideal:'environment'}})}));expect(h.found).toHaveBeenCalledWith(uri,expect.objectContaining({issuer:'GitHub'}));expect(stop).toHaveBeenCalledOnce();expect(h.video.srcObject).toBe(null);expect(h.panel.hidden).toBe(true);});
  it('stops a camera stream that resolves after the dialog was closed',async()=>{const h=harness(),stop=vi.fn();let resolve!:(s:any)=>void;vi.stubGlobal('navigator',{mediaDevices:{getUserMedia:()=>new Promise(r=>resolve=r)}});const pending=h.scanner.camera();h.scanner.stop();resolve({getTracks:()=>[{stop}]});await pending;expect(stop).toHaveBeenCalledOnce();expect(h.found).not.toHaveBeenCalled();expect(h.panel.hidden).toBe(true);});
  it('offers the image fallback when camera permission is denied',async()=>{const h=harness();vi.stubGlobal('navigator',{mediaDevices:{getUserMedia:async()=>{throw Object.assign(new Error(),{name:'NotAllowedError'});}}});await h.scanner.camera();expect(h.status).toHaveBeenLastCalledWith(expect.stringContaining('permission was denied'),true);expect(h.panel.hidden).toBe(true);});
  it('decodes an uploaded image locally and frees the bitmap',async()=>{const h=harness(),close=vi.fn();vi.stubGlobal('createImageBitmap',vi.fn().mockResolvedValue({width:200,height:200,close}));await h.scanner.image(new File(['test-image'],'qr.png',{type:'image/png'}));expect(h.found).toHaveBeenCalledWith(uri,expect.objectContaining({issuer:'GitHub'}));expect(close).toHaveBeenCalledOnce();});
  it('does not populate a closed dialog when image decoding finishes late',async()=>{const h=harness(),close=vi.fn();let resolve!:(b:any)=>void;vi.stubGlobal('createImageBitmap',()=>new Promise(r=>resolve=r));const pending=h.scanner.image(new File(['image'],'qr.png',{type:'image/png'}));h.scanner.stop();resolve({width:200,height:200,close});await pending;expect(h.found).not.toHaveBeenCalled();expect(close).toHaveBeenCalledOnce();});
  it('rejects unsupported image types and oversized files before decoding',async()=>{const h=harness(),decode=vi.fn();vi.stubGlobal('createImageBitmap',decode);await h.scanner.image(new File(['<svg/>'],'qr.svg',{type:'image/svg+xml'}));expect(h.status).toHaveBeenLastCalledWith(expect.stringContaining('Choose a PNG'),true);await h.scanner.image({type:'image/png',size:13*1024*1024} as File);expect(h.status).toHaveBeenLastCalledWith(expect.stringContaining('smaller than 12 MB'),true);expect(decode).not.toHaveBeenCalled();});
});
